Bank feed
payhawk/xero-integration pull request #75
Opened 2020-10-20 12:40 UTC by vassildinev

2020-10-20 13:11 UTC, Boyko-Karadzhov requested changes

2020-10-21 07:04 UTC, vassildinev commented on assets/migration.sql
> +    "account_id" text NOT NULL,
In order to export a bank statement line, we first need to open a bank feed connection (entity in Xero).

2020-10-21 07:05 UTC, vassildinev commented on assets/migration.sql
> +    "currency" text UNIQUE NOT NULL,
Yes, it is a mistake

2020-10-21 14:46 UTC, Boyko-Karadzhov approved these changes

2020-10-21 14:52 UTC, merged