Tax objects
payhawk/xero-integration pull request #86
Opened 2020-11-13 11:21 UTC by vassildinev

2020-11-17 15:45 UTC, Boyko-Karadzhov requested changes

2020-11-17 15:45 UTC, Boyko-Karadzhov commented on Dev.Dockerfile
> +ENV TESTING=true
```
ENV TESTING=true \
        LOG_LEVEL="error" \
        CI=true
```

Every Dockerfile command creates a new layer. Combine them when possible

2020-11-18 15:28 UTC, viktor-skarlatov commented on src/services/xero/http/HttpClient.ts
> +                    return undefined as any;
Wouldn't it be better to change the return type to support undefined?

2020-11-18 15:40 UTC, viktor-skarlatov approved these changes

2020-11-19 07:13 UTC, vassildinev commented on src/services/xero/http/HttpClient.ts
> +                    return undefined as any;
Maybe it would be, yes, I'll try it. I just find it annoying to check everywhere for undefined afterwards.

2020-11-27 08:44 UTC, merged